config/routes.rb
Rails.application.routes.draw do

  # Main application entry point (root path)
  root controller: :home, action: :index

  # Routes to manage the images
  resources :images do
    post :search, on: :collection
  end

  # Sandbox paths to test the API
  get :sandbox, controller: :sandbox, action: :index
  post :sandbox, controller: :sandbox, action: :index

  # Documentation path
  get :docs, controller: :docs, action: :index
  get :about, controller: :about, action: :index

  # API entrypoints
  scope '/api' do
    get :images, controller: :api, action: :images, as: :api_images
    get :not_found, controller: :api, action: :not_found, as: :api_not_found
    get '*path' => redirect('/api/not_found')
  end

  # Handle missing paths
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  # Media holding the image source
  has_attached_file :media, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'

  # Image media validation
  validates :media, presence: true
  validates_attachment_content_type :media, content_type: %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}

  # Image post-processing
  before_save :extract_dimensions

  # Validate and serialize the tags
  serialize :tags, Array
  validates :tags, presence: true

  # Validate the dimensions
  validates :width, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
  validates :height, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  # Scope to filter images based on tags
  scope :tagged, ->(tags) { where(tags.map{|tag| "tags LIKE '%#{tag}%'"}.join(' AND ')) }

  private

  # Extract image width and height
  def extract_dimensions

    # Do not do the image processing if the model is not valid
    return unless valid?

    # Extract the dimension reading from files properties
    tempfile = media.queued_for_write[:original]
    if tempfile.present?
      geometry = Paperclip::Geometry.from_file(tempfile)

      # Store values on the columns
      self.width = geometry.width.to_i
      self.height = geometry.height.to_i
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  class ApiError < Exception;end
  before_action :set_default_response_format

  # API exception manager
  rescue_from Exception do |e|
    @error = e.message
    render 'api/error', status: :internal_server_error
  end

  def images

    # Get parameters
    @tags = params[:tags].to_s.split(/\s*,\s*/) || []
    @limit = params[:limit]

    # Validate parameters
    unless @limit.blank? || /\A\d+\z/.match(@limit)
      raise ApiError, 'Limit must be an integer'
    end

    # Search images based on given filter
    @images = Image.tagged(@tags).limit(@limit.present? ? @limit.to_i : nil)

    # Render the correct status code
    render 'api/images', status: :ok

  rescue ApiError => e

    # Handle errors
    @error = e.message
    render 'api/error', status: :bad_request
  end

  def not_found

    # Handle resource not found and output error message
    @error = 'Resource not found'
    render 'api/error', status: :not_found
  end

  protected

  # Set response to JSON by default
  def set_default_response_format
    request.format = :json
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # General exception manager
  rescue_from Exception do |e|
    flash[:error] = e.message
    redirect_to root_path
  end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :update_filter
  before_action :get_image, only: [:show, :edit, :update, :destroy]
  before_action :update_siblings, only: [:show, :edit]

  def index
    # Get all images
    @images = Image.tagged(@filter)
  end

  def search
    # Redirect to the index page
    redirect_to images_path(filter: params[:filter])
  end

  def show
  end

  def new
    # Create a new image to populate
    @image = Image.new
  end

  def create
    # Create the new image to store
    @image = Image.new(image_params)

    # Create and notify result
    if @image.save
      flash[:success] = 'Image successfully created'

      # Warn about hidden elements
      if @filter.present?
        flash[:warning] = 'Actual search filter may hide the new image'
      end
    else
      flash[:error] = @image.errors.full_messages
    end

    # Redirect to the index page
    redirect_to images_path(filter: @filter)
  end

  def edit
  end

  def update

    # Update and notify result
    if @image.update(image_params)
      flash[:success] = 'Image successfully updated'

      # Warn about hidden elements
      if @filter.present?
        flash[:warning] = 'Actual search filter may hide the updated image'
      end
    else
      flash[:error] = @image.errors.full_messages
    end

    # Redirect to the index page
    redirect_to images_path(filter: @filter)
  end

  def destroy

    # Delete and notify result
    if @image.destroy
      flash[:success] = 'Image successfully deleted'
    end

    # Redirect to the index page
    redirect_to images_path(filter: @filter)
  end

  protected

  # Filter allowed parameters to populate the model
  def image_params
    # Clean empty tags first
    params.require(:image)[:tags].reject!{|tag| tag.blank?}
    params.require(:image).permit!
  end

  # Update image filter
  def update_filter
    @filter = (params[:filter] || [])
  end

  # Get current image based on ID parameter
  def get_image
    @image = Image.find(params[:id])
  end

  # Update next and previous elements
  def update_siblings
    @prev = Image.tagged(@filter).where('id < ?', @image.id).last
    @next = Image.tagged(@filter).where('id > ?', @image.id).first
  end
end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController

  def index

    # Set filters based on given parameters
    @tags = params[:tags].to_s.split(/\s*,\s*/) || []
    @limit = params[:limit]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Get bootstrap alert class based on message type
  def get_bootstrap_alert_class(message_type)
    case message_type
      when 'success'
        'alert-success'
      when 'error'
        'alert-danger'
      when 'warning'
        'alert-warning'
      else
        'alert-info'
    end
  end

  # Return URL from path
  def path_to_url(path)
    "#{request.protocol}#{request.host_with_port.sub(/:80$/,"")}/#{path.sub(/^\//,"")}"
  end

end

app/views/about/index.html.erb
<h1>About</h1>

<p class="alert alert-info">
  <%= icon('info-circle') %> <i>Adbum is an academic exercise not ready for production yet. Please see the <a href="#recommendations">recommendations</a> to know what
  needs to be completed.</i>
</p>

<h2>Coding Challenge</h2>

<h3>Requirements</h3>
<p>Create a program that we can use to add promotional images to our advertisements. Our ads vary in size, and so sometimes
  we may include one large image or sometimes we may include several images in a paged gallery within the ad. This program
  can be a command-line program, a library, or an API.</p>

<h3>Expected Input</h3>
<ul>
  <li>Number of images to output</li>
  <li>Image keywords to match as a comma-separated-value, i.e. “blue, flowers, desert”</li>
</ul>

<h3>Expected Output</h3>
<ul>
  <li>Total number of results</li>
  <li>Image URL</li>
  <li>Image Width</li>
  <li>Image Height</li>
</ul>

<p>
  The output format can be a table of HTML data if you feel that is easier, but in most cases simply printing output to
  the command line or screen in a structured format will be good enough.
</p>

<h3>Image Data</h3>
<p>
  You can use a simple hash or array of data, a flat file of data (like JSON or TOML), or you can build a small db table
  if you are so inclined. The data is not as important as the structure of your code, your functions, and the ability for us to run your code with this test data.
</p>

<h2>Design Overview</h2>

<p class="alert alert-info">
  <%= icon('info-circle') %> <i>Critical requirements based on the challenge are marked in red.</i>
</p>

<h3>Use Cases</h3>
<p>
  In order to solve this challenges, we need to gather the critical requirements. Here we expanded the original requirements
  to deliver a more usable solution:
</p>
<p>
  <%= image_tag 'use_cases.png' %>
</p>

<h3>Architectural Overview</h3>
<p>
  Based on critical requirements, we put together a simple design to structure the application:
</p>
<p>
  <%= image_tag 'architectural_overview.png' %>
</p>

<h3>Data Model</h3>
<p>
  What data needs to be stored and queried? See the following diagram:
</p>
<p>
  <%= image_tag 'data_model.png' %>
</p>

<h2>Recommendations</h2>

<p>To extend and make this solution a production ready application, we recommend the following add-ons and improvements:</p>

<ul id="recommendations">
  <li>Add <a href="https://github.com/plataformatec/devise">users and roles to manage</a> the <%= link_to 'repository', images_path %></li>
  <li>Add token based <a href="https://www.pluralsight.com/guides/ruby-ruby-on-rails/token-based-authentication-with-ruby-on-rails-5-api">authentication/authorization</a> to secure the API</li>
  <li>Add <a href="https://github.com/kaminari/kaminari">pagination</a> to the repository index page</li>
</ul>

<h2>Author</h2>
<p>Copyright (c) 2017 <a href="https://www.linkedin.com/in/mario-enrique-s%C3%A1nchez-749a1a89/">Mario Enrique Sanchez</a></p>

<p class="alert alert-success">
  <i>
    Permission is hereby granted, <b>free of charge, to any person obtaining
    a copy of this software</b> and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the Software
    is furnished to do so, subject to the following conditions:

    <b>The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.</b>
  </i>
</p>

app/views/docs/index.html.erb
<h1>Docs</h1>
<p>Adbum is a minimalistic <b>API</b> to retrieve images on demand. This product is inspired by the need of getting images based
  on keywords for advertisement campaigns. The reference describes each available resource in the API, so you can learn
  about parameters, errors, and result formats.</p>

<h2>Entry Point</h2>
<p>To access the API yo need to use the following <b>URL</b>:</p>
<% api_url = path_to_url('api/images') %>
<code><%= api_url %></code>

<h2>Parameters</h2>
<p>Adbum uses two <b>GET</b> parameters:</p>
<ul>
  <li><b>tags </b> <i>(String) [Optional]</i>: Image keywords to match as a comma separated value. Leave this parameter
    blank to not filter. Retrieved images must contain all tags</li>
  <li><b>limit </b> <i>(Integer) [Optional]</i>: Number of images to output. Leave this parameter blank to not limit</li>
</ul>

<h4>Examples</h4>
<pre class="prettyprint well">
  <code class="lang-js">
    "<%= "#{api_url}" %>" // Get all images without limiting the output
    "<%= "#{api_url}?tags=leather,hat" %>" // Get images by tags but not limiting the output
    "<%= "#{api_url}?limit=20" %>" // Get images limiting just the output
    "<%= "#{api_url}?tags=cute,cat&limit=20" %>" // Get images by tags and also limiting the output
  </code>
</pre>

<h2>Reponses</h2>
Since Adbum is a Restful JSON API, the response will be a well formatted JSON object.

<h3>Ok <small>(Response Code: 200)</small></h3>
<p>This is the regular response, counting and listing available images based on tags and limited on demand.</p>
<pre class="prettyprint well">
  <code class="lang-js">
  {
    "count": Integer, // How many images were found
    "images": [
      {
        "url": String, // Image URL
        "width": Integer, // Image Width
        "height": Integer // Image height
      },
    ]
  }

  // Example: "<%= "#{api_url}?tags=cute,cat&limit=3" %>"
  {
    "count": 3
    "images": [
      {
        "url": "http://0.0.0.0:5000/system/images/media/000/000/033/original/cute_kitty.jpg?1487212007",
        "width": 568,
        "height": 568
      },
      {
        "url": "http://0.0.0.0:5000/system/images/media/000/000/035/original/charles.jpg?1487212264",
        "width": 568,
        "height": 568
      },
      {
        "url": "http://0.0.0.0:5000/system/images/media/000/000/036/original/persian_ball.png?1487212285",
        "width": 590,
        "height": 590
      }
    ]
  }
  </code>
</pre>

<h3>Bad Request <small>(Response Code: 400)</small></h3>
<p>This response happens when the request is malformed. In other words, the parameters sent by the API consumer
  didn't follow the rules.</p>
<pre class="prettyprint well">
  <code class="lang-js">
  {
    "error": String // Error message
  }

  // Example: "<%= "#{api_url}?limit=all" %>"
  {
    "error": "Limit must be an integer"
  }
  </code>
</pre>

<h3>Not Found <small>(Response Code: 404)</small></h3>
<p>This response happens when an API consumer try to access to a no existing resource.</p>
<pre class="prettyprint well">
  <code class="lang-js">
  {
    "error": String // Error message
  }

  // Example: "<%= "#{api_url}/wrong" %>"
  {
    "error": "Resource not found"
  }
  </code>
</pre>

<h3>Internal Server Error <small>(Response Code: 500)</small></h3>
<p>This response happens when there is some uncaught error, usually a system exception. The error message comes from the exception.</p>
<pre class="prettyprint well">
  <code class="lang-js">
  {
    "error": String // Error message
  }

  // Example: "<%= "#{api_url}" %>"
  // Then something bad happens
  {
    "error": "Something went really bad internally. Please call 911! ;)"
  }
  </code>
</pre>

app/views/home/index.html.erb
<h1>Home</h1>

<%= render partial: 'shared/messages' %>

<p class="lead well">
  Adbum is a minimalistic API to retrieve images on demand. We store and serve the media, you just need to use them!
</p>

<h2>Motivation</h2>
<p>
  Some advertisement agencies need to display images based on keywords for their campaigns. Adbum is a simple but
  reliable way of getting images based on tags. Our clients do not need to store and process the media, they just need to
  manage and catalog them trough our <%= link_to 'repository', images_path %>. Are you ready? Please visit our
  <%= link_to 'documentation', docs_path %> and feel free to play in the <%= link_to 'sandbox', sandbox_path %>.
</p>

<h2>Getting Started</h2>

<p>
  First of all, you need to build the <%= link_to 'repository', images_path %> using our web console. You can
  upload as many images as you want, specifying the tags to retrieve them later. To get the list of images,
  you just need to provide two arguments: <b>tags</b> and <b>limit</b>. Please see the following example:
</p>

<h4>Java Script</h4>
<pre class="prettyprint well">
  <code class="lang-js">
    $.getJSON('<%= "#{path_to_url('api/images')}?tags=cute,cat&limit=20" %>', function(data){
        console.log(data);
    });
  </code>
</pre>

app/views/images/_form.html.erb
<%
  # Control if this view is rendered to create or update an image
  edit = @image.persisted?
%>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for @image, authenticity_token: true, html: {multipart: true} do |f| %>

      <% @filter.each do |tag| %>
        <%= hidden_field_tag 'filter[]', tag %>
      <% end %>

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= edit ? 'Edit' : 'New' %> Image</h4>
      </div>

      <div class="modal-body">
        <div class="form-group">
          <% if @image.media.exists? %>
            <%= image_tag @image.media.url(:medium), class: 'center-block' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :tags %>
          <%= f.select :tags, @image.tags, {}, multiple: :multiple, include_blank: false %>
        </div>

        <div class="form-group">
          <%= f.label :media %>
          <%= f.file_field :media, class: 'form-control' %>
        </div>
      </div>

      <div class="modal-footer">
        <% if edit %>
          <%= link_to image_path(@image.id, filter: @filter), method: :delete, class: 'btn btn-danger pull-left' do %>
            Remove
          <% end %>

          <% if @prev.present? %>
            <%= link_to edit_image_path(@prev, filter: @filter), remote: true, class: 'btn btn-default' do %>
              Prev
            <% end %>
          <% end %>

          <% if @next.present? %>
            <%= link_to edit_image_path(@next, filter: @filter), remote: true, class: 'btn btn-default' do %>
              Next
            <% end %>
          <% end %>
        <% end %>

        <%= f.submit edit ? 'Update' : 'Create', class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/images/_load_form.js.erb
// Get the image dialog component
var imageDialog = $('#imageDialog');

// Load content
imageDialog.html("<%= j(render partial: 'form') %>");

// Convert the tag editor into a token select
var tagEditor = $('#image_tags');
tagEditor.select2({
    tags: true,
    tokenSeparators: [',', ' '],
    width: '100%',
    minimumResultsForSearch: Infinity
});

// Show the image dialog
imageDialog.modal('show');

app/views/images/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Image Details</h4>
    </div>

    <div class="modal-body">
      <% if @image.media.exists? %>
        <%= link_to @image.media.url, target: '_blank' do %>
          <%= image_tag @image.media.url(:medium), class: 'center-block' %>
        <% end %>
      <% end %>
    </div>

    <div class="modal-footer">
      <div class="pull-left">

        <%= link_to image_path(@image, filter: @filter), method: :delete, class: 'btn btn-danger' do %>
          Remove
        <% end %>
      </div>

      <%= link_to edit_image_path(@image, filter: @filter), remote: true, class: 'btn btn-default' do %>
        Edit
      <% end %>

      <% if @prev.present? %>
        <%= link_to image_path(@prev, filter: @filter), remote: true, class: 'btn btn-primary' do %>
          Prev
        <% end %>
      <% end %>

      <% if @next.present? %>
        <%= link_to image_path(@next, filter: @filter), remote: true, class: 'btn btn-primary' do %>
          Next
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/images/edit.js.erb
<%= render 'load_form' %>

app/views/images/index.html.erb
<h1>Repository</h1>

<nav class="navbar navbar-default">
  <div class="container-fluid">

    <%= form_tag search_images_path, class: 'navbar-form navbar-left' do %>
      <div class="form-group">
        <%= select_tag 'filter[]', options_for_select(@filter.map{|tag| [tag, tag]}, @filter), multiple: :multiple, include_blank: false %>
        <%= submit_tag 'Search', class: 'btn btn-default' %>
      </div>
    <% end %>

    <ul class="nav navbar-nav">
      <li><a href="#"><b><%= @images.size %></b> images found</a></li>
    </ul>

    <div class="navbar-form navbar-right">
      <%= link_to new_image_path(filter: @filter), remote: true, class: 'btn btn-primary pull-right' do %>
        Add
      <% end %>
    </div>
  </div>
</nav>

<%= render partial: 'shared/messages' %>

<%#= Group images by rows of 4 %>
<% @images.each_slice(4) do |row| %>
  <div class="row">
    <% row.each do |image| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_path(image, filter: @filter), remote: true do %>
            <%= image_tag image.media.url(:medium) %>
          <% end %>
          <div class="caption">

            <ul class="list-unstyled">
              <li><b>Dimensions:</b> <%= image.width %> X <%= image.height %></li>
              <li><b>Tags:</b> <%= image.tags.join(', ') %></li>
            </ul>

            <%= link_to image_path(image, filter: @filter), method: :delete, class: 'btn btn-danger pull-left' do %>
              Remove
            <% end %>

            <%= link_to edit_image_path(image, filter: @filter), remote: true, class: 'btn btn-default pull-right' do %>
              Edit
            <% end %>

            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div id="imageDialog" class="modal"></div>

app/views/images/new.js.erb
<%= render 'load_form' %>

app/views/images/show.js.erb
// Get the image dialog component
var imageDialog = $('#imageDialog');

// Load content
imageDialog.html("<%= j(render partial: 'show') %>");

// Show the image dialog
imageDialog.modal('show');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body onload="PR.prettyPrint()">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainNavbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Adbum', root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="mainNavbar">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if controller_name == 'home' %>">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="<%= 'active' if controller_name == 'images' %>">
              <%= link_to 'Repository', images_path, class: 'nav-link' %>
            </li>
            <li class="<%= 'active' if controller_name == 'sandbox' %>">
              <%= link_to 'Sandbox', sandbox_path, class: 'nav-link' %>
            </li>
            <li class="<%= 'active' if controller_name == 'docs' %>">
              <%= link_to 'Docs', docs_path, class: 'nav-link' %>
            </li>
            <li class="<%= 'active' if controller_name == 'about' %>">
              <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sandbox/index.html.erb
<%
  # Prepare some parameters we need
  api_url = path_to_url('api/images')
  tags = @tags.join(',')
  limit = @limit
  query = "#{api_url}?tags=#{tags}&limit=#{limit}"
%>

<h1>Sandbox</h1>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= form_tag sandbox_path, class: 'navbar-form navbar-left' do %>
      <div class="form-group">
        <code><span id="url"><%= api_url %></span>?tags=</code>
        <%= text_field_tag 'tags', tags, class: 'form-control' %>
        <code>&limit=</code>
        <%= text_field_tag 'limit', @limit, class: 'form-control' %>
        <%= submit_tag 'Query', class: 'btn btn-primary' %>
      </div>
    <% end %>

    <div class="navbar-form navbar-right">
      <%= link_to query, class: 'btn btn-default', target: '_blank' do %>
        GO
      <% end %>
    </div>
  </div>
</nav>

<h2>Result</h2>
<pre class="well">
  <code id="result" class="lang-js"></code>
</pre>

app/views/shared/_messages.html.erb
<div id="messages">
  <% flash.each do |type, message| %>

    <div class="alert <%= get_bootstrap_alert_class(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>

      <% if message.is_a? Array %>
        <ul>
          <% message.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% else %>
        <%= message %>
      <% end %>
    </div>

  <% end %>
  <% flash.clear %>
</div>